### PR TITLE
Feature login screen, Setup screen, and basic routing

### PR DESCRIPTION
**Pull request by jcsmileyjr**
This is a multi-feature update:
1. Login screen looks like the wireframe. The only thing missing is the background images that gives the screen life. 
2. Setup screen looks like the wireframe. My only concern is the spacing. While the Next button is at the bottom and is better for mobile, it is far down on the screen for desktop users. 
3. Next button functionality included so users can move from one stage of setup to the next (3 stages). 
3. Basic routing between the Login and Setup screens.

Short video of current progress including the Next button functionality. 
 routing-1

### CODE REVIEW

**Comment by xamthor** [comment]
Feedback and Changes

1. When the create button is push it should go to create account view, not the setup screen

2. Remove outline when typing text into input fields 
image

3 on desktop, using the tailwindcss class cursor-pointer will show the pointer when hovering over the next text

4. in the setup screen, if the page is reloaded it goes back to the first stage, allow the setup screen to remember the user stage 

5.  View Adobe XD file to see updated desktop design.

**Comment by jcsmileyjr** [comment]
1. Do we have a mockup of the create account view. I was under the impression the setup screens was that functionality. 
2. When the user starts typing, the default will automactic delete the placeholder text. I will see if I can't find a way to delete when the curser is in the input field. 
3 -4 . Will do
5. I love that picture.

**Comment by xamthor** [comment]
Here is the the create account view I am referencing 

image

**Comment by jcsmileyjr** [comment]
I have completed 4 of the 5 suggestions from the pull request.

   1. remove outline in input field
   2. cursor pointer shows over Next and other fields similar to it
   3. Routing from Create button to "create account screen" to setup screens
   4. New logo picture on desktop view.

**Pull request merged**
